  <main role="main">    <h1>Class PrivilegedActionException</h1>   <ul class="inheritance"> <li><a href="../lang/object">java.lang.Object</a></li> <li> <ul class="inheritance"> <li><a href="../lang/throwable">java.lang.Throwable</a></li> <li> <ul class="inheritance"> <li><a href="../lang/exception">java.lang.Exception</a></li> <li> <ul class="inheritance"> <li>java.security.PrivilegedActionException</li> </ul> </li> </ul> </li> </ul> </li> </ul>   <dl> <dt>All Implemented Interfaces:</dt> <dd><code><a href="../io/serializable">Serializable</a></code></dd> </dl>  <pre data-language="java">public class PrivilegedActionException
extends Exception</pre> <div>
<p>This exception is thrown by <code>doPrivileged(PrivilegedExceptionAction)</code> and <code>doPrivileged(PrivilegedExceptionAction,
 AccessControlContext context)</code> to indicate that the action being performed threw a checked exception. The exception thrown by the action can be obtained by calling the <code>getException</code> method. In effect, an <code>PrivilegedActionException</code> is a "wrapper" for an exception thrown by a privileged action. </p>
<p>As of release 1.4, this exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The "exception thrown by the privileged computation" that is provided at construction time and accessed via the <a href="#getException()"><code>getException()</code></a> method is now known as the <i>cause</i>, and may be accessed via the <a href="../lang/throwable#getCause()"><code>Throwable.getCause()</code></a> method, as well as the aforementioned "legacy method."</p>
</div> <dl> <dt>Since:</dt> <dd>1.2</dd> <dt>See Also:</dt> <dd>
<a href="privilegedexceptionaction"><code>PrivilegedExceptionAction</code></a>, <a href="accesscontroller#doPrivileged(java.security.PrivilegedExceptionAction)"><code>AccessController.doPrivileged(PrivilegedExceptionAction)</code></a>, <a href="accesscontroller#doPrivileged(java.security.PrivilegedExceptionAction,java.security.AccessControlContext)"><code>AccessController.doPrivileged(PrivilegedExceptionAction,AccessControlContext)</code></a>, <a href="https://docs.oracle.com/en/java/javase/11/docs/api/serialized-form.html#java.security.PrivilegedActionException">Serialized Form</a>
</dd> </dl>      <section role="region">  <h2 id="constructor.summary">Constructors</h2> <table>  <tr> <th scope="col">Constructor</th> <th scope="col">Description</th> </tr> <tr> <th scope="row"><code><a href="#%3Cinit%3E(java.lang.Exception)">PrivilegedActionException</a>​(<a href="../lang/exception">Exception</a> exception)</code></th> <td> <p>Constructs a new PrivilegedActionException "wrapping" the specific Exception.</p> </td> </tr> </table>  </section>  <section role="region">  <h2 id="method.summary">Methods</h2> <table>  <tr> <th scope="col">Modifier and Type</th> <th scope="col">Method</th> <th scope="col">Description</th> </tr> <tr id="i0"> <td><code><a href="../lang/throwable">Throwable</a></code></td> <th scope="row"><code><a href="#getCause()">getCause</a>()</code></th> <td> <p>Returns the cause of this exception (the exception thrown by the privileged computation that resulted in this <code>PrivilegedActionException</code>).</p> </td> </tr> <tr id="i1"> <td><code><a href="../lang/exception">Exception</a></code></td> <th scope="row"><code><a href="#getException()">getException</a>()</code></th> <td> <p>Returns the exception thrown by the privileged computation that resulted in this <code>PrivilegedActionException</code>.</p> </td> </tr> </table>  <h2 id="methods.inherited.from.class.java.lang.Throwable">Methods declared in class java.lang.<a href="../lang/throwable">Throwable</a>
</h2> <code><a href="../lang/throwable#addSuppressed(java.lang.Throwable)">addSuppressed</a>, <a href="../lang/throwable#fillInStackTrace()">fillInStackTrace</a>, <a href="../lang/throwable#getLocalizedMessage()">getLocalizedMessage</a>, <a href="../lang/throwable#getMessage()">getMessage</a>, <a href="../lang/throwable#getStackTrace()">getStackTrace</a>, <a href="../lang/throwable#getSuppressed()">getSuppressed</a>, <a href="../lang/throwable#initCause(java.lang.Throwable)">initCause</a>, <a href="../lang/throwable#printStackTrace()">printStackTrace</a>, <a href="../lang/throwable#printStackTrace(java.io.PrintStream)">printStackTrace</a>, <a href="../lang/throwable#printStackTrace(java.io.PrintWriter)">printStackTrace</a>, <a href="../lang/throwable#setStackTrace(java.lang.StackTraceElement%5B%5D)">setStackTrace</a>, <a href="../lang/throwable#toString()">toString</a></code>  <h2 id="methods.inherited.from.class.java.lang.Object">Methods declared in class java.lang.<a href="../lang/object">Object</a>
</h2> <code><a href="../lang/object#clone()">clone</a>, <a href="../lang/object#equals(java.lang.Object)">equals</a>, <a href="../lang/object#finalize()">finalize</a>, <a href="../lang/object#getClass()">getClass</a>, <a href="../lang/object#hashCode()">hashCode</a>, <a href="../lang/object#notify()">notify</a>, <a href="../lang/object#notifyAll()">notifyAll</a>, <a href="../lang/object#wait()">wait</a>, <a href="../lang/object#wait(long)">wait</a>, <a href="../lang/object#wait(long,int)">wait</a></code>  </section>   <div>   <section role="region">  <h2 id="constructor.detail">Constructors</h2>   <h3 id="&lt;init&gt;(java.lang.Exception)">PrivilegedActionException</h3> <pre data-language="java">public PrivilegedActionException(Exception exception)</pre> <p>Constructs a new PrivilegedActionException "wrapping" the specific Exception.</p> <dl> <dt>Parameters:</dt> <dd>
<code>exception</code> - The exception thrown</dd> </dl>   </section>  <section role="region">  <h2 id="method.detail">Methods</h2>   <h3 id="getException()">getException</h3> <pre data-language="java">public Exception getException()</pre> <div>
<p>Returns the exception thrown by the privileged computation that resulted in this <code>PrivilegedActionException</code>. </p>
<p>This method predates the general-purpose exception chaining facility. The <a href="../lang/throwable#getCause()"><code>Throwable.getCause()</code></a> method is now the preferred means of obtaining this information.</p>
</div> <dl> <dt>Returns:</dt> <dd>the exception thrown by the privileged computation that resulted in this <code>PrivilegedActionException</code>.</dd> <dt>See Also:</dt> <dd>
<a href="privilegedexceptionaction"><code>PrivilegedExceptionAction</code></a>, <a href="accesscontroller#doPrivileged(java.security.PrivilegedExceptionAction)"><code>AccessController.doPrivileged(PrivilegedExceptionAction)</code></a>, <a href="accesscontroller#doPrivileged(java.security.PrivilegedExceptionAction,java.security.AccessControlContext)"><code>AccessController.doPrivileged(PrivilegedExceptionAction,
                                            AccessControlContext)</code></a>
</dd> </dl>    <h3 id="getCause()">getCause</h3> <pre data-language="java">public Throwable getCause()</pre> <p>Returns the cause of this exception (the exception thrown by the privileged computation that resulted in this <code>PrivilegedActionException</code>).</p> <dl> <dt>Overrides:</dt> <dd>
<code><a href="../lang/throwable#getCause()">getCause</a></code> in class <code><a href="../lang/throwable">Throwable</a></code>
</dd> <dt>Returns:</dt> <dd>the cause of this exception.</dd> <dt>Since:</dt> <dd>1.4</dd> </dl>   </section>  </div>  </main>  <div class="_attribution">
  <p class="_attribution-p">
    &copy; 1993, 2020, Oracle and/or its affiliates. All rights reserved.<br>Documentation extracted from Debian's OpenJDK Development Kit package.<br>Licensed under the GNU General Public License, version 2, with the Classpath Exception.<br>Various third party code in OpenJDK is licensed under different licenses (see Debian package).<br>Java and OpenJDK are trademarks or registered trademarks of Oracle and/or its affiliates.<br>
    <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/PrivilegedActionException.html" class="_attribution-link">https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/PrivilegedActionException.html</a>
  </p>
</div>
