  <main role="main">    <h1>Interface ExceptionEvent</h1>     <dl> <dt>All Superinterfaces:</dt> <dd>
<code><a href="event">Event</a></code>, <code><a href="../locatable">Locatable</a></code>, <code><a href="locatableevent">LocatableEvent</a></code>, <code><a href="../mirror">Mirror</a></code>
</dd> </dl>  <pre data-language="java">public interface ExceptionEvent
extends LocatableEvent</pre> <p>Notification of an exception in the target VM. When an exception is thrown which satisfies a currently enabled <a href="../request/exceptionrequest"><code>exception request</code></a>, an <a href="eventset"><code>event set</code></a> containing an instance of this class will be added to the VM's event queue. If the exception is thrown from a non-native method, the exception event is generated at the location where the exception is thrown. If the exception is thrown from a native method, the exception event is generated at the first non-native location reached after the exception is thrown.</p> <dl> <dt>Since:</dt> <dd>1.3</dd> </dl>      <section role="region">  <h2 id="method.summary">Methods</h2> <table>  <tr> <th scope="col">Modifier and Type</th> <th scope="col">Method</th> <th scope="col">Description</th> </tr> <tr id="i0"> <td><code><a href="../location">Location</a></code></td> <th scope="row"><code><a href="#catchLocation()">catchLocation</a>()</code></th> <td> <p>Gets the location where the exception will be caught.</p> </td> </tr> <tr id="i1"> <td><code><a href="../objectreference">ObjectReference</a></code></td> <th scope="row"><code><a href="#exception()">exception</a>()</code></th> <td> <p>Gets the thrown exception object.</p> </td> </tr> </table>  <h2 id="methods.inherited.from.class.com.sun.jdi.event.Event">Methods declared in interface com.sun.jdi.event.<a href="event">Event</a>
</h2> <code><a href="event#request()">request</a></code>  <h2 id="methods.inherited.from.class.com.sun.jdi.Locatable">Methods declared in interface com.sun.jdi.<a href="../locatable">Locatable</a>
</h2> <code><a href="../locatable#location()">location</a></code>  <h2 id="methods.inherited.from.class.com.sun.jdi.event.LocatableEvent">Methods declared in interface com.sun.jdi.event.<a href="locatableevent">LocatableEvent</a>
</h2> <code><a href="locatableevent#thread()">thread</a></code>  <h2 id="methods.inherited.from.class.com.sun.jdi.Mirror">Methods declared in interface com.sun.jdi.<a href="../mirror">Mirror</a>
</h2> <code><a href="../mirror#toString()">toString</a>, <a href="../mirror#virtualMachine()">virtualMachine</a></code>  </section>   <div>   <section role="region">  <h2 id="method.detail">Methods</h2>   <h3 id="exception()">exception</h3> <pre data-language="java">ObjectReference exception()</pre> <p>Gets the thrown exception object. The exception object is an instance of <a href="../../../../../java.base/java/lang/throwable"><code>Throwable</code></a> or a subclass in the target VM.</p> <dl> <dt>Returns:</dt> <dd>an <a href="../objectreference"><code>ObjectReference</code></a> which mirrors the thrown object in the target VM.</dd> </dl>    <h3 id="catchLocation()">catchLocation</h3> <pre data-language="java">Location catchLocation()</pre> <div>
<p>Gets the location where the exception will be caught. An exception is considered to be caught if, at the point of the throw, the current location is dynamically enclosed in a try statement that handles the exception. (See the JVM specification for details). If there is such a try statement, the catch location is the first code index of the appropriate catch clause. </p>
<p> If there are native methods in the call stack at the time of the exception, there are important restrictions to note about the returned catch location. In such cases, it is not possible to predict whether an exception will be handled by some native method on the call stack. Thus, it is possible that exceptions considered uncaught here will, in fact, be handled by a native method and not cause termination of the target VM. Furthermore, it cannot be assumed that the catch location returned here will ever be reached by the throwing thread. If there is a native frame between the current location and the catch location, the exception might be handled and cleared in that native method instead. </p>
<p> Note that the compiler can generate try-catch blocks in some cases where they are not explicit in the source code; for example, the code generated for <code>synchronized</code> and <code>finally</code> blocks can contain implicit try-catch blocks. If such an implicitly generated try-catch is present on the call stack at the time of the throw, the exception will be considered caught even though it appears to be uncaught from examination of the source code.</p>
</div> <dl> <dt>Returns:</dt> <dd>the <a href="../location"><code>Location</code></a> where the exception will be caught or null if the exception is uncaught.</dd> </dl>   </section>  </div>  </main>  <div class="_attribution">
  <p class="_attribution-p">
    &copy; 1993, 2020, Oracle and/or its affiliates. All rights reserved.<br>Documentation extracted from Debian's OpenJDK Development Kit package.<br>Licensed under the GNU General Public License, version 2, with the Classpath Exception.<br>Various third party code in OpenJDK is licensed under different licenses (see Debian package).<br>Java and OpenJDK are trademarks or registered trademarks of Oracle and/or its affiliates.<br>
    <a href="https://docs.oracle.com/en/java/javase/11/docs/api/jdk.jdi/com/sun/jdi/event/ExceptionEvent.html" class="_attribution-link">https://docs.oracle.com/en/java/javase/11/docs/api/jdk.jdi/com/sun/jdi/event/ExceptionEvent.html</a>
  </p>
</div>
